# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ ];
      kernelModules = [ ];
    };
    kernelPackages = (import (builtins.fetchTarball https://gitlab.com/vriska/nix-rpi5/-/archive/main.tar.gz)).legacyPackages.aarch64-linux.linuxPackages_rpi5;
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
      device = "/dev/disk/by-uuid/0a29886f-751a-4e93-aaa1-50212ba74779";
      fsType = "ext4";
  };

  fileSystems."/mnt" = {
      device = "/dev/disk/by-uuid/b9be788b-cf58-407a-bf62-714be3961910";
      fsType = "ext4";
  };

  fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/D113-AE85";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
